"use client"
import { useState, type ComponentType, type ReactNode } from "react"
import { BriefcaseBusiness, ChevronDown, CircleDollarSign, FileText, ShieldAlert, TrendingUp, Users } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import { ADMIN_DASHBOARD_PERIODS, type AdminDashboardPeriod } from "@/lib/admin-dashboard-period"
import type { AdminDashboardActionType, AdminDashboardResponse } from "@/types/admin-dashboard-api"

const visuals: Record<AdminDashboardActionType, { icon: ComponentType<{ className?: string }>; className: string }> = { PendingOnboardingReview: { icon: ShieldAlert, className: "bg-[#FDE8EA] text-[#F43F5E]" }, DraftCampaign: { icon: FileText, className: "bg-[#FFF6D9] text-[#F4B400]" }, PaymentException: { icon: CircleDollarSign, className: "bg-[#E8F6F1] text-[#087A67]" } }
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount)

function StatCard({ title, value, icon: Icon, featured = false, footer }: { title: string; value: string; icon: ComponentType<{ className?: string }>; featured?: boolean; footer: ReactNode }) {
  return <article className={cn("min-h-[210px] rounded-lg border p-5 lg:p-6", featured ? "border-[#033B32] bg-[#033B32] text-white" : "border-[#E4E7EC] bg-white text-[#1F1F1F]")}><div className={cn("mb-7 flex size-12 items-center justify-center rounded-md", featured ? "bg-white text-[#1F1F1F]" : "bg-[#F4F7F6] text-[#073F35]")}><Icon className="size-6" /></div><p className={cn("text-base", featured ? "text-white/90" : "text-[#8A8D89]")}>{title}</p><p className="mt-1 text-[32px] font-semibold leading-tight">{value}</p><div className={cn("mt-4 flex items-center gap-2 text-sm", featured ? "text-white" : "text-[#8A8D89]")}>{footer}</div></article>
}

export function AdminDashboard({ data, isLoading, period, onPeriodChange }: { data?: AdminDashboardResponse; isLoading: boolean; period: AdminDashboardPeriod; onPeriodChange: (period: AdminDashboardPeriod) => void }) {
  const [showAll, setShowAll] = useState(false); const summary = data?.summary; const actions = data?.actions ?? []; const activity = data?.recentActivity ?? []; const shown = showAll ? actions : actions.slice(0, 3); const currency = summary?.currency ?? "NGN"; const growth = summary?.investorGrowthPercent; const growthText = growth == null ? `${summary?.newInvestorsInPeriod ?? 0} new in period` : `${growth >= 0 ? "+" : ""}${growth}% vs previous period`
  return <main className="pb-6"><section className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-[30px] font-semibold text-[#1F1F1F] md:text-[34px]">Command Center</h1><p className="mt-1 text-base text-[#5F625F] md:text-lg">Monitor platform activity, performance, and operations in real time</p></div><div className="relative w-full sm:w-auto"><select aria-label="Dashboard reporting period" value={period} onChange={(e) => onPeriodChange(e.target.value as AdminDashboardPeriod)} className="h-12 w-full rounded-md border border-[#A8AAA8] bg-white px-4 pr-10 sm:w-[170px]">{ADMIN_DASHBOARD_PERIODS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-5 -translate-y-1/2" /></div></section>
    {isLoading ? <section aria-label="Loading platform overview" className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((n) => <Skeleton key={n} className="min-h-[210px]" />)}</section> : <section aria-label="Platform overview" className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3"><StatCard featured title="Total Investors" value={(summary?.totalInvestors ?? 0).toLocaleString()} icon={Users} footer={<><TrendingUp className="size-5" /><span>{growthText}</span></>} /><StatCard title="Active Campaigns" value={(summary?.activeCampaigns ?? 0).toLocaleString()} icon={TrendingUp} footer={<><strong className="text-[#A8BD27]">{money(summary?.activeCampaignRaisedAmount ?? 0, currency)}</strong><span>raised</span></>} /><StatCard title="Total Campaigns" value={(summary?.totalCampaigns ?? 0).toLocaleString()} icon={BriefcaseBusiness} footer={<><strong className="text-[#A8BD27]">{money(summary?.totalFundsRaised ?? 0, currency)}</strong><span>total funds raised</span></>} /></section>}
    <section className="mt-7 grid grid-cols-1 gap-5 xl:grid-cols-2"><article className="rounded-xl border border-[#DDE4ED] bg-white p-5 md:p-6"><div className="flex items-center justify-between border-b border-[#E7E9E7] pb-5"><h2 className="text-lg font-semibold">Action Required</h2>{actions.length > 3 && <Button variant="link" onClick={() => setShowAll(!showAll)}>View All</Button>}</div><div className="space-y-4 pt-6">{shown.map((item) => { const Visual = visuals[item.type]; const Icon = Visual.icon; return <div key={item.type} className="flex flex-col gap-4 rounded-lg border border-[#E7EBEF] bg-[#F8FAFC] p-4 sm:flex-row sm:items-center"><div className={cn("flex size-12 shrink-0 items-center justify-center rounded-md", Visual.className)}><Icon className="size-6" /></div><div className="min-w-0 flex-1"><h3 className="font-medium">{item.title}</h3><p className="text-sm text-[#70809A]">{item.description}</p></div>{item.route && <Button asChild variant="outline"><a href={item.route}>Review</a></Button>}</div> })}</div>{actions.length > 3 && <Button variant="outline" onClick={() => setShowAll(!showAll)} className="mt-7 w-full">{showAll ? "Show less" : "Show all"}</Button>}</article><article className="rounded-xl border border-[#DDE4ED] bg-white p-5 md:p-6"><div className="border-b border-[#E7E9E7] pb-5"><h2 className="text-lg font-semibold">Recent Activity</h2></div><ol className="pt-3">{activity.map((item, index) => <li key={item.id} className="relative flex gap-4 py-4">{index < activity.length - 1 && <span className="absolute left-[5px] top-7 h-[calc(100%-12px)] w-px bg-[#EDF0ED]" />}<span className="relative mt-2 size-2.5 shrink-0 rounded-full bg-[#B0C63B]" /><div><p className="text-[15px] leading-6">{item.description}</p><p className="mt-1 text-sm text-[#8A8D89]">{new Date(item.occurredAtUtc).toLocaleString()}</p></div></li>)}</ol>{!isLoading && activity.length === 0 && <p className="py-8 text-sm text-[#8A8D89]">No recent activity to display.</p>}</article></section>
  </main>
}
