"use client";

import Image from "next/image";
import { ArrowLeft, CheckCircle2, MessageSquare, X } from "lucide-react";
import { useState } from "react";
import type { AdminInvestorDetail } from "@/types/admin-investors-api";
import { OnboardingButton } from "@/components/onboarding/molecules/OnboardingButton";

interface KycReviewPageProps {
    investor: AdminInvestorDetail;
    onBack: () => void;
    onUpdate: (payload: { kycStatus: string; note: string }) => void;
    isUpdating: boolean;
}

const documents = ["ID Document", "Proof of address", "Selfie"];

export function KycReviewPage({ investor, onBack, onUpdate, isUpdating }: KycReviewPageProps) {
    const [document, setDocument] = useState("Selfie");
    const [requestOpen, setRequestOpen] = useState(false);
    const [confirmAction, setConfirmAction] = useState<"approve" | "reject" | null>(null);
    const [deadline, setDeadline] = useState("7");
    const [message, setMessage] = useState(`Dear ${investor.firstName}, we reviewed your KYC submission and need the selected information before we can proceed.`);
    const [channels, setChannels] = useState<string[]>(["Email", "In App"]);
    const [rejectReason, setRejectReason] = useState("");
    const [selected, setSelected] = useState(["Clearer copy of government-issued ID", "Proof of address (utility bill or bank statement less than 3 months old)"]);
    const name = `${investor.firstName} ${investor.lastName}`;
    const submitted = investor.kycReviewedAt ? new Date(investor.kycReviewedAt).toLocaleDateString() : new Date(investor.joinedAt).toLocaleDateString();
    const toggle = (value: string) => setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);

    const displayStatus = investor.kycStatus === "DocumentsRequested" ? "Info Requested" : investor.kycStatus === "Pending" ? "Pending KYC" : investor.kycStatus;
    const activeDocument = investor.kycReview.documents.find((item) => (document === "ID Document" ? item.type === "Identity" : document === "Proof of address" ? item.type === "ProofOfAddress" : item.type === "Selfie"));
    const documentUrl = activeDocument?.pathOrKey || "/admin-investor-profile/identityCardMockup.png";
    return <div className="space-y-6 pb-8">
        <button type="button" onClick={onBack} className="inline-flex items-center gap-2 text-[#666] hover:text-[#111]"><ArrowLeft className="h-5 w-5" /> Back to Pending KYC</button>
        <section className="flex flex-wrap items-center justify-between gap-5 rounded-xl border border-[#EAEAEA] bg-white p-5">
            <div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full border border-[#BDBDBD] text-2xl text-[#505050]">{investor.firstName[0]}{investor.lastName[0]}</div><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{name}</h1><span className="rounded-md bg-[#FFF7E6] px-2 py-1 text-xs text-[#C58A00]">{displayStatus}</span></div><p className="text-sm text-[#858585]">{investor.investorId} • {investor.email}</p><p className="mt-1 text-sm text-[#858585]">Submitted {submitted}</p></div></div>
            <div className="flex flex-wrap gap-3"><OnboardingButton label="Request more info" variant="plain" icon={<MessageSquare className="h-4 w-4" />} onClick={() => setRequestOpen(true)} className="my-0 w-fit" /><OnboardingButton label="Reject KYC" variant="plain" icon={<X className="h-4 w-4" />} onClick={() => setConfirmAction("reject")} className="my-0 w-fit border-[#E5484D] text-[#D4001A]" /><OnboardingButton label="Approve KYC" icon={<CheckCircle2 className="h-4 w-4" />} onClick={() => setConfirmAction("approve")} disabled={isUpdating} className="my-0 w-fit" /></div>
        </section>
        <div className="grid grid-cols-1 gap-6 xl:grid-cols-[0.8fr_1.2fr]">
            <div className="space-y-6"><InfoCard title="Personal Information"><Info label="Full name" value={name} /><Info label="Date of birth" value={investor.dateOfBirth ? new Date(investor.dateOfBirth).toLocaleDateString() : "Not provided"} /><Info label="Phone number" value={investor.phoneNumber || "Not provided"} /><Info label="Email address" value={investor.email} /><Info label="Residential address" value={[investor.residentialAddress, investor.stateOfResidence, investor.countryOfResidence].filter(Boolean).join(", ") || "Not provided"} /></InfoCard><InfoCard title="BVN Verification">{investor.kycReview.checks.map((check) => <div key={check.name} className="flex items-center justify-between border-b border-[#F0F0F0] py-3 last:border-0"><span className="text-[#666]">{check.name}</span><span className={`flex items-center gap-1 text-sm ${check.passed ? "text-[#35A935]" : "text-[#D4001A]"}`}>{check.passed && <CheckCircle2 className="h-4 w-4" />} {check.passed ? "Pass" : "Not verified"}</span></div>)}</InfoCard></div>
            <div className="space-y-6"><InfoCard title="Submitted Documents"><div className="mb-5 flex flex-wrap gap-2">{documents.map((item) => <button type="button" key={item} onClick={() => setDocument(item)} className={`rounded-lg border px-4 py-2 text-sm ${document === item ? "border-[#35645C] bg-[#35645C] text-white" : "border-[#E5E5E5]"}`}>{item}</button>)}</div><div className="flex items-center justify-between"><h3 className="font-semibold">{document === "Selfie" ? "Selfie Liveness match" : document}</h3><span className="rounded-lg bg-[#E5F9E4] px-3 py-2 text-sm font-semibold text-[#35A935]">✓ 96% match</span></div><div className="relative mt-4 aspect-[16/8] overflow-hidden rounded-xl bg-[#F2F2F2]"><Image src={documentUrl} alt={`${document} preview`} fill className="object-cover" /></div><div className="mt-3 flex gap-4 text-sm"><a href={documentUrl} target="_blank" rel="noreferrer" className="font-medium text-[#6D9A2B]">Full view ↗</a><a href={documentUrl} download className="font-medium text-[#6D9A2B]">Download</a></div><p className="mt-3 text-sm text-[#858585]">ⓘ Face geometry match score via identity API</p></InfoCard><InfoCard title="OCR Extracted Data"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[["Last Name", investor.lastName], ["First Name", investor.firstName], ["Date of Birth", investor.dateOfBirth ? new Date(investor.dateOfBirth).toLocaleDateString() : "Not provided"], ["Gender", "Not provided"], ["Nationality", investor.countryOfResidence || "Not provided"], ["Expiry Date", "Not provided"]].map(([label, value]) => <div key={label} className="rounded-lg border border-[#EAEAEA] p-4"><p className="text-xs text-[#858585]">{label}</p><p className="mt-1 font-semibold">{value}</p><p className="text-xs text-[#35A935]">✓ Match submitted data</p></div>)}</div></InfoCard></div>
        </div>
        <InfoCard title="Review History"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-[#35A935]" /><div><p className="font-medium">{investor.kycStatus} review status</p><p className="text-sm text-[#666]">{investor.kycReviewNote || "KYC submission received and queued for review."}</p><p className="mt-1 text-xs text-[#858585]">{investor.kycReviewedAt ? new Date(investor.kycReviewedAt).toLocaleString() : "No review decision recorded yet"}</p></div></div></InfoCard>
        {requestOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Request More Information</h2><button type="button" onClick={() => setRequestOpen(false)} aria-label="Close request information"><X /></button></div><p className="mt-1 text-sm text-[#666]">Select the information required before KYC can proceed.</p><div className="mt-5 space-y-3">{["Clearer copy of government-issued ID", "Proof of address (utility bill or bank statement less than 3 months old)", "Updated selfie with ID held next to face", "Source of funds declaration", "Director / beneficial ownership documents"].map((item) => <label key={item} className="flex items-center gap-3 rounded-lg border border-[#EAEAEA] p-3"><input type="checkbox" checked={selected.includes(item)} onChange={() => toggle(item)} />{item}</label>)}</div><label className="mt-5 block text-sm font-medium">Response deadline<select value={deadline} onChange={(event) => setDeadline(event.target.value)} className="mt-2 w-full rounded-lg border border-[#EAEAEA] p-3"><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option></select></label><label className="mt-4 block text-sm font-medium">Message to investor<textarea value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-[#EAEAEA] p-3" /></label><div className="mt-4"><p className="text-sm font-medium">Notify investor</p><div className="mt-2 flex gap-4">{["Email", "In App", "SMS"].map((channel) => <label key={channel} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={channels.includes(channel)} onChange={() => setChannels((current) => current.includes(channel) ? current.filter((item) => item !== channel) : [...current, channel])} />{channel}</label>)}</div></div><p className="mt-4 rounded-lg bg-[#FFF8E7] p-3 text-sm text-[#795C00]">Sending this request changes the KYC status to Info Requested and sets a {deadline}-day response window.</p><div className="mt-6 flex justify-end gap-3"><OnboardingButton label="Cancel" variant="plain" onClick={() => setRequestOpen(false)} className="my-0 w-fit" /><OnboardingButton label="Send Request" disabled={!selected.length || !message.trim() || !channels.length || isUpdating} onClick={() => { onUpdate({ kycStatus: "DocumentsRequested", note: `Request (${deadline} days; ${channels.join(", ")}): ${message.trim()} Required: ${selected.join(", ")}.` }); setRequestOpen(false); }} className="my-0 w-fit" /></div></div></div>}
        {confirmAction && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-xl font-semibold">{confirmAction === "approve" ? "Approve KYC?" : "Reject KYC?"}</h2><p className="mt-2 text-sm text-[#666]">This decision will be recorded against {name} and update their KYC status.</p>{confirmAction === "reject" && <textarea aria-label="Rejection reason" value={rejectReason} onChange={(event) => setRejectReason(event.target.value)} placeholder="Enter rejection reason" className="mt-4 min-h-24 w-full rounded-lg border border-[#EAEAEA] p-3" /> }<div className="mt-6 flex justify-end gap-3"><OnboardingButton label="Cancel" variant="plain" onClick={() => { setConfirmAction(null); setRejectReason(""); }} className="my-0 w-fit" /><OnboardingButton label={confirmAction === "approve" ? "Confirm approval" : "Confirm rejection"} disabled={isUpdating || (confirmAction === "reject" && !rejectReason.trim())} onClick={() => { onUpdate({ kycStatus: confirmAction === "approve" ? "Approved" : "Rejected", note: confirmAction === "approve" ? "KYC approved after manual document review." : rejectReason.trim() }); setConfirmAction(null); setRejectReason(""); }} className="my-0 w-fit" /></div></div></div>}
    </div>;
}

function InfoCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[#EAEAEA] bg-white p-5"><h2 className="mb-4 border-b border-[#EAEAEA] pb-4 text-lg font-semibold">{title}</h2>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="mb-4 last:mb-0"><p className="text-sm text-[#858585]">{label}</p><p className="mt-1 text-base">{value}</p></div>; }
